@Server_HostAddress = http://localhost:5413

### Get all projects
GET {{Server_HostAddress}}/api/projects
Accept: application/json

###

### Get project by id
GET {{Server_HostAddress}}/api/projects/00000000-0000-0000-0000-000000000000
Accept: application/json

###

### Create project
POST {{Server_HostAddress}}/api/projects
Content-Type: application/json

{
  "name": "My Project",
  "description": "A sample project description"
}

###

### Update project
PUT {{Server_HostAddress}}/api/projects/00000000-0000-0000-0000-000000000000
Content-Type: application/json

{
  "name": "Updated Project Name",
  "description": "Updated description"
}

###

### Delete project
DELETE {{Server_HostAddress}}/api/projects/00000000-0000-0000-0000-000000000000

###

### Get epic by id
GET {{Server_HostAddress}}/api/epics
Accept: application/json

###

### Create epic
POST {{Server_HostAddress}}/api/epics
Content-Type: application/json

{
  "name": "Patrick Star"
}

###

### Update epic
PUT {{Server_HostAddress}}/api/epics/019dec44-f51c-7dbb-b836-ba42d223dfe9
Content-Type: application/json

{
  "name": "king kong",
  "description": "cheatday i swear"
}

###

### Delete epic
DELETE {{Server_HostAddress}}/api/epics/019dec46-0dde-7d8a-9682-0fb372b8ad95

###
