@Server_HostAddress = http://localhost:5413

### Get all epics
GET {{Server_HostAddress}}/api/epics
Accept: application/json

###

### Get epic by id
GET {{Server_HostAddress}}/api/epics/019dec46-0dde-7d8a-9682-0fb372b8ad95
Accept: application/json

###

### Create epic
POST {{Server_HostAddress}}/api/epics
Content-Type: application/json

{
  "name": "Wambo"
}

###

### Update epic
PUT {{Server_HostAddress}}/api/epics/019dec46-0dde-7d8a-9682-0fb372b8ad95
Content-Type: application/json

{
  "name": "Monkeytype",
  "description": "eatsleep"
}

###

### Delete epic
DELETE {{Server_HostAddress}}/api/epics/019dec46-0dde-7d8a-9682-0fb372b8ad95

###
