@Server_HostAddress = http://localhost:5413

### Get all epics
GET {{Server_HostAddress}}/api/epics
Accept: application/json

###

### Get epic by id
GET {{Server_HostAddress}}/api/epics/019dec56-e6f9-7566-a4db-77fba07fcd41
Accept: application/json

###

### Create epic
POST {{Server_HostAddress}}/api/epics
Content-Type: application/json

{
  "name": "Patrick Star"
}

###

### Update epic
PUT {{Server_HostAddress}}/api/epics/019dec44-f51c-7dbb-b836-ba42d223dfe9
Content-Type: application/json

{
  "name": "king kong",
  "description": "cheatday i swear"
}

###

### Delete epic
DELETE {{Server_HostAddress}}/api/epics/019dec46-0dde-7d8a-9682-0fb372b8ad95

###
